filetype off
filetype plugin indent off

" カラースキームを指定
colorscheme torte
"colorscheme koehler

" フォントサイズをデフォルトより小さいサイズに変更
"set guifont=MS_Gothic:h9:cSHIFTJIS
" 改行コードの自動判別
set fileformats=unix,dos,mac

" 文字エンコーディングの指定
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,iso-2022-jp-3,iso-2022-jp,eucjp-ms,euc-jisx0213,euc-jp,sjis,cp932,utf-8

" バックスペースで「行頭の空白」、「改行」、
" 「挿入モード開始位置より手前」を削除できるように
set backspace=indent,eol,start

" 保存していない編集をバックアップ
set writebackup
" バックアップの保存先を指定
set backupdir=$HOME/.vim/backup
" swpファイルの保存先を指定
set directory=$HOME/.vim/swpfile
" undoファイルの保存先を指定
set undodir=$HOME/.vim/undo

" 検索時に大文字が含まれている場合は区別する
set ignorecase
set smartcase
" 最後まで検索したら先頭に戻さない
set nowrapscan
" インクリメンタルサーチ
set incsearch

" 必ずvimgrepを使用する
"set grepprg=internal

" 行番号を表示
set number
" Ctrl-Iでタブ文字表示を行わない
"set list
" 対応する括弧を表示
set showmatch
" 実行途中の入力を右下に表示
set showcmd
" テキストの最大幅の制約を無効化する
set textwidth=0
" テキストの折り返しを行わない
set nowrap

" オートインデントを有効にする
set autoindent
" スマートインデントも有効にする(EMACSライクのオートインデントは使用しない)
set smartindent
set nocindent

" タブの文字数を指定
set tabstop=4
" タブ、バックスペース使用時の編集操作を行うときのタブの幅
set softtabstop=2
" オートインデント時のタブの幅
set shiftwidth=2
" タブを挿入するときに空白に置きかえる
set expandtab

" ファイルタイプを表示
set laststatus=2
set statusline=%y

source $VIMRUNTIME/macros/matchit.vim

" インデント操作を連続して行えるようにする
vnoremap < <gv
vnoremap > >gv

" クリップボードにヤンクした内容を共有する
set clipboard=unnamed

" 端末上でマウスを使えるようにする
set mouse=a
set ttymouse=xterm2

" 端末上でキャレットをモードに合わせて変化させる(記法はDECSCUSRを参照)
let &t_SI .= "\e[5 q"
let &t_SR .= "\e[3 q"
let &t_EI .= "\e[1 q"

" 指定のコマンド実行時に必ずQuickfixを開く
"autocmd QuickfixCmdPost vimgrep if len(getqflist())!=0 | copen | endif
autocmd QuickfixCmdPost vimgrep cw
autocmd QuickfixCmdPost lvimgrep lw

filetype plugin indent on

